#nullable enable
using System;
using System.IO;
using System.Xml;
using UnityEditor.Android;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;

namespace Anathema.Net.Editor
{
    /// <summary>
    /// Grava <c>android:usesCleartextTraffic</c> no manifesto da unityLibrary: <c>true</c> em
    /// build de desenvolvimento, <c>false</c> em produção. O <c>false</c> é explícito porque o
    /// <c>minSdk</c> é 23 e, até a API 27, o padrão do Android libera cleartext. A liberação do
    /// Unity (<c>insecureHttpOption</c>) não chega ao manifesto
    /// (specs/001-server-connection/research.md, R3). Usa o gancho pós-geração do Gradle
    /// porque, no 6000.2, o manifesto da unityLibrary não é público no
    /// <c>AndroidProjectFilesModifier</c>.
    /// </summary>
    /// <example>
    /// <code>
    /// DevCleartextManifest.ApplyTo("Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/src/main/AndroidManifest.xml", cleartext: false);
    /// </code>
    /// </example>
    public sealed class DevCleartextManifest : IPreprocessBuildWithReport, IPostGenerateGradleAndroidProject
    {
        private const string AndroidNamespace = "http://schemas.android.com/apk/res/android";

        // O gancho pós-geração não recebe o relatório; o tipo do build vem do pré-build da mesma
        // execução. Estático porque o Unity cria uma instância por gancho.
        private static bool developmentBuild;

        /// <summary>Ordem entre os ganchos de build.</summary>
        /// <example><code>int order = new DevCleartextManifest().callbackOrder;</code></example>
        public int callbackOrder => 0;

        /// <summary>Valor do atributo para o tipo de build.</summary>
        /// <example><code>bool value = DevCleartextManifest.CleartextValueFor(developmentBuild: false); // false</code></example>
        public static bool CleartextValueFor(bool isDevelopmentBuild) => isDevelopmentBuild;

        /// <summary>Guarda se este build é de desenvolvimento.</summary>
        /// <example><code>hook.OnPreprocessBuild(report);</code></example>
        public void OnPreprocessBuild(BuildReport report)
        {
            developmentBuild = (report.summary.options & UnityEditor.BuildOptions.Development) != 0;
        }

        /// <summary>Aplica o atributo no manifesto da unityLibrary recém-gerada.</summary>
        /// <example><code>hook.OnPostGenerateGradleAndroidProject(unityLibraryPath);</code></example>
        public void OnPostGenerateGradleAndroidProject(string path)
        {
            ApplyTo(Path.Combine(path, "src", "main", "AndroidManifest.xml"), CleartextValueFor(developmentBuild));
        }

        /// <summary>Grava o atributo em <c>&lt;application&gt;</c> do manifesto no caminho dado.</summary>
        /// <example><code>DevCleartextManifest.ApplyTo(manifestPath, cleartext: true);</code></example>
        public static void ApplyTo(string manifestPath, bool cleartext)
        {
            XmlDocument manifest = new XmlDocument();
            manifest.Load(manifestPath);
            XmlElement application = manifest.SelectSingleNode("/manifest/application") as XmlElement
                ?? throw new InvalidOperationException($"{manifestPath} has no <application>: expected the unityLibrary manifest generated by Unity");

            application.SetAttribute("usesCleartextTraffic", AndroidNamespace, cleartext ? "true" : "false");
            manifest.Save(manifestPath);
        }
    }
}
